project_id = "zhwwvmhsmofucgejqpcm"

[functions.test-hcp-connection]
verify_jwt = false

[functions.sync-hcp-data]
verify_jwt = false

[functions.test-rc-connection]
verify_jwt = false

[functions.sync-rc-calls]
verify_jwt = false

[functions.rc-oauth-callback]
verify_jwt = false

[functions.suggest-job-time]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.import-youtube-playlist]
verify_jwt = false

[functions.send-checklist-notifications]
verify_jwt = false

[functions.create-hcp-job]
verify_jwt = false

[functions.update-hcp-job]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-inventory-notifications]
verify_jwt = false
